dist: xenial
sudo: false
language: python
matrix:
  include:
  - python: "2.7"
    env: TOXENV=py27
  - python: "3.4"
    env: TOXENV=py34
  - python: "3.5"
    env: TOXENV=py35
  - python: "3.6"
    env: TOXENV=py36
  - python: "3.7"
    env: TOXENV=py37
  - python: "2.7"
    env: TOXENV=pep8py2
  - python: "3.6"
    env: TOXENV=pep8py3
  - python: "2.7"
    env: TOXENV=packagepy2
  - python: "3.7"
    env: TOXENV=packagepy3
install: pip install tox
script: tox
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - peter@pakos.uk
