#!/usr/bin/env python
#
# A tool to send mail using WDMail library
#
# Author: Peter Pakos <peter.pakos@wandisco.com>

from __future__ import print_function

import argparse
import os
import platform
import sys

import WDMail


class Main(object):
    _version = '16.8.3'
    _cwd = os.path.dirname(os.path.realpath(__file__))
    _name = os.path.basename(os.path.realpath(__file__))

    def __init__(self):
        args = self._parse_args()

        self._api_file = '%s/%s.api' % (self._cwd, self._name)
        self._api_key = None

        if os.path.isfile(self._api_file):
            f = open(self._api_file)
            self._api_key = f.readline().strip()
        if self._api_key is None:
            print('Sendgrid API key not found in file %s' % self._api_file)
            exit(1)

        if args.sender:
            sender = args.sender
        else:
            sender = os.getenv('USER') + '@' + platform.node()
        message = ''
        for line in sys.stdin:
            message += line

        email = WDMail.WDMail(api_key=self._api_key)
        status = email.send(sender, args.recipients, args.subject, message, args.html, args.cc)
        if status < 300:
            exit()
        else:
            print('\nError')
            exit(1)

    def _parse_args(self):
        parser = argparse.ArgumentParser(description='A tool to send mail via sendgrid')
        parser.add_argument('--version', action='version', version='%s %s' % (self._name, self._version))
        parser.add_argument('-f', '--from', dest='sender',
                            help='email From: field')
        parser.add_argument('-t', '--to', dest='recipients', nargs='+', required=True,
                            help='email To: field')
        parser.add_argument('-c', '--cc', dest='cc', nargs='+',
                            help='email Cc: field')
        parser.add_argument('-s', '--subject', dest='subject', required=True,
                            help='email Subject: field')
        parser.add_argument('-H', '--html', dest='html', action='store_true',
                            help='send HTML formatted email')
        args = parser.parse_args()
        return args

    def _display_version(self):
        print('%s %s' % (self._name, self._version))


if __name__ == '__main__':
    try:
        main = Main()
    except KeyboardInterrupt:
        print('\nCancelling...')
